version: "3.1"
services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    # stop 상태가 되지 않는 이상 재시작
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Container 내의 시간대를 대한민국으로 설정
      TZ: Asia/Seoul
      # code-space에 진입할 때 비밀번호를 입력하게 할려면 이 내용을 설정
      PASSWORD: "PASSWORD"
      # 기본 Workspace 위치 지정 (Container 내 경로로)
      DEFAULT_WORKSPACE: /config/workspace
    volumes:
      # VSCode의 설정이 저장될 위치 -> 컨테이너가 재시작 되어도 설정이 초기화 되지 않도록 조치
      - {"HOME DIRECTORY"}/.config/code-server:/config
      # Workspace을 Host와 연결
      - {"PROJECT DIRECTORY"}:/config/workspace
      
volumes:
  codespace-config:
